#! /bin/bash

#Function Creation
#-----------------
#Main Class Functions
function createMain(){
  touch "$NAME".java

  echo  "public class "$NAME"{" >> "$NAME".java
  echo  "    public static void main(String[] args){" >> "$NAME".java
  echo  "      " >> "$NAME".java
  echo  "    }" >> "$NAME".java
  echo  "}" >> "$NAME".java
}
#-----------------
function replaceMain(){
  echo  "public class "$NAME"{" > "$NAME".java
  echo  "    public static void main(String[] args){" >> "$NAME".java
  echo  "      " >> "$NAME".java
  echo  "    }" >> "$NAME".java
  echo  "}" >> "$NAME".java
}
#-----------------
#Public Class Functions
function createPublicClass(){
  touch "$NAME".java

  echo  "public class "$NAME"{" >> "$NAME".java
  echo  "	  " >> "$NAME".java
  echo  "}" >> "$NAME".java
}
#-----------------
function replacePublicClass(){
  echo  "public class "$NAME"{" > "$NAME".java
  echo  "	  " >> "$NAME".java
  echo  "}" >> "$NAME".java
}
#-----------------
#Private Class Functions
function createPrivateClass(){
  touch "$NAME".java

  echo  "private class "$NAME"{" >> "$NAME".java
  echo  "	  " >> "$NAME".java
  echo  "}" >> "$NAME".java
}
#-----------------
function replacePrivateClass(){
  echo  "private class "$NAME"{" > "$NAME".java
  echo  "	  " >> "$NAME".java
  echo  "}" >> "$NAME".java
}
#-----------------
#Private Class Functions
function createPrivateClass(){
  touch "$NAME".java

  echo  "abstract class "$NAME"{" >> "$NAME".java
  echo  "	  " >> "$NAME".java
  echo  "}" >> "$NAME".java
}
#-----------------
function replacePrivateClass(){
  echo  "abstract class "$NAME"{" > "$NAME".java
  echo  "	  " >> "$NAME".java
  echo  "}" >> "$NAME".java
}
#-----------------

case $1 in

#Main Class Creation Flag
  --main)
    if [ "$2" != "" ];
    then
      NAME=$2
      if [ ! -f ./"$NAME".java ];
      then
        createMain
      else
        echo "Class Already Exists"
        echo "Replace File? y/n"

        read INPUT
        case $INPUT in

          y)
            replaceMain
            ;;

          Y)
            replaceMain
            ;;

          *)
            echo "Cancelling Class Creation"
            ;;
        esac
      fi
    else
      echo "Missing Name Flag"
    fi
    ;;

#Public Class Creation Flag
  --public-class)
    if [ "$2" != "" ]
    then
      NAME=$2
      if [ ! -f ./"$NAME".java ];
      then
        createPublicClass
      else
        echo "Class Already Exists"
        echo "Replace File? y/n"

        read INPUT 
        case $INPUT in

          y)
            replacePublicClass
            ;;

          Y)
            replacePublicClass
            ;;

          *)
            echo "Cancelling Class Creation"
            ;;
        esac
      fi
    else
      echo "Missing Name Flag"
    fi  
    ;;

#Private Class Creation Flag
  --private-class)
    if [ "$2" != "" ]
    then
      NAME=$2
      if [ ! -f ./"$NAME".java ];
      then
        createPrivateClass
      else
        echo "Class Already Exists"
        echo "Replace File? y/n"

        read INPUT
        case $INPUT in

          y)
            replacePrivateClass
            ;;

          Y)
            replacePrivateClass
            ;;

          *)
            echo "Cancelling Class Creation"
            ;;
        esac
      fi
    else
      echo "Missing Name Flag"
    fi  
    ;;
#Private Class Creation Flag
  --abstract-class)
    if [ "$2" != "" ]
    then
      NAME=$2
      if [ ! -f ./"$NAME".java ];
      then
        createPrivateClass
      else
        echo "Class Already Exists"
        echo "Replace File? y/n"

        read INPUT
        case $INPUT in

          y)
            replacePrivateClass
            ;;

          Y)
            replacePrivateClass
            ;;

          *)
            echo "Cancelling Class Creation"
            ;;
        esac
      fi
    else
      echo "Missing Name Flag"
    fi  
    ;;

#Help Menu
  --help)
    echo "--main : create a public class containing a main function"
    echo "--public-class : create an empty public class"
    echo "--private-class : create an empty private class"
	echo "--abstract-class : create an empty abstract class"
    ;;

  *)
    echo "Invalid Flag: Try createjc --help to see a list of available flags"
    ;;
esac


